version: "3.1"
services:
  devserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/development_server_setup:latest
    command: make
    environment:
      DO_PAT: $DO_PAT
    volumes:
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa