---
- name: Install software using package managers
  hosts: inspector
  tasks:
    - name: Update system
      apt:
        update_cache: true
      become: true
    - name: Install cURL
      apt:
        name: "curl"
        state: present
      become: true
    - name: Install Docker
      apt:
        name: "docker.io"
        state: present
      become: true
    - name: Install Docker-compose
      apt:
        name: "docker-compose"
        state: present
      become: true
    - name: Install Git
      apt:
        name: "git"
        state: present
      become: true
    - name: Install Make
      apt:
        name: "make"
        state: present
      become: true
    - name: Install pip
      apt:
        name: "python3-pip"
        state: present
      become: true
    - name: Install Docker SDK for Python
      pip:
        name: docker
      notify: Restart server
    - name: Add '{{ ansible_user_id }}' to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      become: true
      notify: Restart server
  handlers:
    - name: Restart server
      reboot:
      become: true

- name: Install analislas dotfiles
  hosts: devservers
  tasks:
    - name: Clone analislas dotfiles
      git:
        repo: https://github.com/analislas/dotfiles.git
        dest: "{{ ansible_facts.user_dir }}/dotfiles/"
        clone: true
        update: true
        version: develop
    - name: Run 'install' analislas dotfiles
      make:
        chdir: "{{ ansible_facts.user_dir }}/dotfiles"
        target: install
      become: true

- name: Install geci-testmake using ad hoc installation
  hosts: devservers
  tasks:
    - name: Clone testmake repository
      git:
        repo: https://github.com/IslasGECI/testmake.git
        dest: "{{ ansible_facts.user_dir }}/testmake/"
        clone: true
        update: true
        version: develop
    - name: Run 'install' testmake
      make:
        chdir: "{{ ansible_facts.user_dir }}/testmake"
        target: install

- name: Set system up
  hosts: devservers
  tasks:
    - name: Configura huso horario
      timezone:
        name: America/Los_Angeles
      become: true
    - name: Ensure group "share" exists
      group:
        name: share
        state: present
    - name: Recursively change ownership of share directory
      ansible.builtin.file:
        path: "/tmp/share"
        state: directory
        recurse: true
        group: share
        mode: g+rws,o+rwx
    - name: Copy scripts
      copy:
        src: /src
        dest: "{{ ansible_facts.user_dir }}"
        mode: +x
      notify: crontab
  handlers:
    - name: crontab
      command: "crontab {{ ansible_facts.user_dir }}/src/Cronfile"
      become: true

- name: Tests
  hosts: devservers
  tasks:
    - name: Prueba Docker
      docker_container:
        name: islasgeci_base
        image: islasgeci/base
