---
- name: Install software using package managers
  hosts: devserver
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install cURL
      ansible.builtin.apt:
        name: "curl"
        state: present
      become: true
    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Install Git
      ansible.builtin.apt:
        name: "git"
        state: present
      become: true
    - name: Install Make
      ansible.builtin.apt:
        name: "make"
        state: present
      become: true
    - name: Install pip
      ansible.builtin.apt:
        name: "python3-pip"
        state: present
      become: true
    - name: Install pipx
      ansible.builtin.apt:
        name: "pipx"
        state: present
      become: true
    - name: Install Docker SDK for Python
      community.general.pipx:
        name: docker
        install_deps: true
      notify: Restart server
    - name: Add to docker group '{{ ansible_user_id }}'
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      become: true
      notify: Restart server
  handlers:
    - name: Restart server
      ansible.builtin.reboot:
      become: true

- name: Install IslasGECI dotfiles
  hosts: devserver
  tasks:
    - name: Clone IslasGECI dotfiles
      ansible.builtin.git:
        repo: https://github.com/IslasGECI/dotfiles.git
        dest: "{{ ansible_facts.user_dir }}/dotfiles/"
        clone: true
        update: true
        version: develop
    - name: Install IslasGECI dotfiles
      community.general.make:
        chdir: "{{ ansible_facts.user_dir }}/dotfiles"
        target: install
      become: true

- name: Install geci-testmake using ad hoc installation
  hosts: devserver
  tasks:
    - name: Clone testmake repository
      ansible.builtin.git:
        repo: https://github.com/IslasGECI/testmake.git
        dest: "{{ ansible_facts.user_dir }}/testmake/"
        clone: true
        update: true
        version: develop
    - name: Run 'install' testmake
      community.general.make:
        chdir: "{{ ansible_facts.user_dir }}/testmake"
        target: install_in_container
      become: true

- name: Set system up
  hosts: devserver
  tasks:
    - name: Configura huso horario
      community.general.timezone:
        name: America/Los_Angeles
      become: true
    - name: Ensure group "share" exists
      ansible.builtin.group:
        name: share
        state: present
      become: true
    - name: Recursively change ownership of share directory
      ansible.builtin.file:
        path: "/tmp/share"
        state: directory
        recurse: true
        group: share
        mode: g+rws,o+rwx
      become: true
    - name: Copy scripts
      ansible.builtin.copy:
        src: /workdir/src
        dest: "{{ ansible_facts.user_dir }}"
        mode: +x
      notify: Crontab
      become: true
  handlers:
    - name: Crontab
      ansible.builtin.command: "crontab {{ ansible_facts.user_dir }}/src/Cronfile"
      become: true
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0

- name: Tests
  hosts: devserver
  tasks:
    - name: Pull PDE Docker image
      community.docker.docker_container:
        name: islasgeci_pde
        image: islasgeci/pde
