---
- name: Setup users
  hosts: devserver
  become: true
  vars:
    users:
      - name: evaro
        github_username: devarops
      - name: nepo
        github_username: nepito
      - name: memo
        github_username: MemoOlv
      - name: mvb
        github_username: mvillasante
  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: ['docker', 'share', 'sudo']
        shell: "/bin/bash"
        password: "$6$islasgeci$uMZ4ssQEWitFBBnkTDrBkDV0LSsDK71p0ZyzN0R/vas3rLNpGlyr5O/mb6VtVfOhWy9ufcz/bILMpZ5DvbGwn1"
      loop: "{{ users }}"

    - name: Set authorized keys taken from URL
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "https://github.com/{{ item.github_username }}.keys"
      loop: "{{ users }}"

    - name: Clone dotfiles
      git:
        repo: "https://github.com/{{ item.github_username }}/dotfiles.git"
        version: develop
        dest: "/home/{{ item.name }}/dotfiles.git"
        bare: true
      loop: "{{ users }}"

    - name: Install dotfiles
      git:
        repo: "/home/{{ item.name }}/dotfiles.git"
        version: develop
        work_tree: "/home/{{ item.name }}"
        force: true
      loop: "{{ users }}"

    - name: Add credentials to user profile
      ansible.builtin.lineinfile:
        path: "/home/{{ item.name }}/.profile"
        line: "source /home/{{ item.name }}/.vault/.secrets"
      loop: "{{ users }}"

    - name: Recursively change ownership of home directory
      ansible.builtin.file:
        path: "/home/{{ item.name }}"
        state: directory
        recurse: true
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      loop: "{{ users }}"
